FROM node:10-slim

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node ./mfc3d5/package*.json ./

RUN npm install

COPY --chown=node ./mfc3d5/ .

RUN npm run build

CMD ["npm", "run", "start:prod"]