version: "3"

services:
  app:
    build: .
    container_name: mfc3desafio5
    working_dir: /home/node/app/mfc3d5
    command: npm run start:dev
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
